// <auto-generated />
using System;
using DigiMenuAPI.Infrastructure.SQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiMenuAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303021320_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@digimenu.app",
                            FullName = "Super Admin",
                            IsActive = true,
                            PasswordHash = "$2a$12$Kn4xvBfyq0QaFY6EHNzA7.PiJwEmV1BQxz/FeEmTJqmFcm3wvUbWe",
                            Role = (byte)255
                        });
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "IsDeleted", "DisplayOrder");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Entradas"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Platos Fuertes"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Postres"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Bebidas"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Bebidas Alcohólicas"
                        });
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "CR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@digimenu.com",
                            IsActive = true,
                            Name = "DigiMenu Platform",
                            Slug = "digimenu-platform"
                        });
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.CompanyModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActivatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlatformModuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlatformModuleId");

                    b.HasIndex("CompanyId", "IsActive");

                    b.HasIndex("CompanyId", "PlatformModuleId")
                        .IsUnique();

                    b.ToTable("CompanyModules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActivatedByUserId = 1,
                            CompanyId = 1,
                            IsActive = true,
                            PlatformModuleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActivatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActivatedByUserId = 1,
                            CompanyId = 1,
                            IsActive = true,
                            PlatformModuleId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActivatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActivatedByUserId = 1,
                            CompanyId = 1,
                            IsActive = true,
                            PlatformModuleId = 3
                        },
                        new
                        {
                            Id = 4,
                            ActivatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ActivatedByUserId = 1,
                            CompanyId = 1,
                            IsActive = true,
                            PlatformModuleId = 4
                        });
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.FooterLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomSvgContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StandardIconId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("StandardIconId");

                    b.HasIndex("CompanyId", "IsDeleted", "DisplayOrder");

                    b.ToTable("FooterLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsDeleted = false,
                            IsVisible = true,
                            Label = "Instagram",
                            StandardIconId = 2,
                            Url = "https://instagram.com/digimenu"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsDeleted = false,
                            IsVisible = true,
                            Label = "WhatsApp",
                            StandardIconId = 3,
                            Url = "https://wa.me/50612345678"
                        });
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.PlatformModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PlatformModules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "RESERVATIONS",
                            Description = "Gestión de reservas de mesas y eventos.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Reservas"
                        },
                        new
                        {
                            Id = 2,
                            Code = "TABLE_MANAGEMENT",
                            Description = "Vista de plano de mesas en tiempo real.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Gestión de Mesas"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ANALYTICS",
                            Description = "Reportes de visitas, productos más vistos y conversiones.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Analytics Avanzados"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ONLINE_ORDERS",
                            Description = "Delivery y take away con integración de pagos.",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Pedidos en Línea"
                        });
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("OfferPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId", "IsDeleted", "DisplayOrder");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 5500m,
                            CategoryId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Ceviche Clásico",
                            ShortDescription = "Fresco ceviche de corvina con limón y culantro."
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 3500m,
                            CategoryId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Patacones con Guacamole",
                            OfferPrice = 3000m,
                            ShortDescription = "Patacones crocantes con guacamole casero."
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 7500m,
                            CategoryId = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Casado Tradicional",
                            ShortDescription = "Arroz, frijoles, ensalada, maduro y carne a elegir."
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 12500m,
                            CategoryId = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Lomo al Chimichurri",
                            OfferPrice = 10900m,
                            ShortDescription = "Lomo de res al punto con salsa chimichurri."
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 8500m,
                            CategoryId = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Bowl Vegano",
                            ShortDescription = "Quinoa, vegetales asados, hummus y tahini."
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 3200m,
                            CategoryId = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Tres Leches",
                            ShortDescription = "Bizcocho esponjoso bañado en tres tipos de leche."
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 3800m,
                            CategoryId = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Brownies con Helado",
                            ShortDescription = "Brownie de chocolate caliente con helado de vainilla."
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 1500m,
                            CategoryId = 4,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Café Americano",
                            ShortDescription = "Café negro de tueste medio."
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 1800m,
                            CategoryId = 4,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Refresco Natural",
                            ShortDescription = "Cas, tamarindo o guanábana. A elegir."
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 2200m,
                            CategoryId = 5,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Imperial",
                            ShortDescription = "Cerveza nacional 355ml bien fría."
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 3500m,
                            CategoryId = 5,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "Guaro Sour",
                            ShortDescription = "Guaro Cacique, limón, azúcar y hielo."
                        });
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("ReservationTime")
                        .HasColumnType("time");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TableNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "IsDeleted", "ReservationDate");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrowserThemeColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CurrencyLocale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("Decimals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.Property<string>("FacebookPixelId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FormRequireAllergies")
                        .HasColumnType("bit");

                    b.Property<bool>("FormRequireBirthday")
                        .HasColumnType("bit");

                    b.Property<bool>("FormRequireComments")
                        .HasColumnType("bit");

                    b.Property<bool>("FormRequireName")
                        .HasColumnType("bit");

                    b.Property<bool>("FormRequirePersons")
                        .HasColumnType("bit");

                    b.Property<bool>("FormRequirePhone")
                        .HasColumnType("bit");

                    b.Property<bool>("FormRequireTable")
                        .HasColumnType("bit");

                    b.Property<bool>("FormShowAllergies")
                        .HasColumnType("bit");

                    b.Property<bool>("FormShowBirthday")
                        .HasColumnType("bit");

                    b.Property<bool>("FormShowComments")
                        .HasColumnType("bit");

                    b.Property<bool>("FormShowName")
                        .HasColumnType("bit");

                    b.Property<bool>("FormShowPersons")
                        .HasColumnType("bit");

                    b.Property<bool>("FormShowPhone")
                        .HasColumnType("bit");

                    b.Property<bool>("FormShowTable")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleAnalyticsId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HeaderBackgroundColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<byte>("HeaderStyle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("HeaderTextColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#000000");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("MenuLayout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageBackgroundColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#E63946");

                    b.Property<string>("PrimaryTextColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<byte>("ProductDisplay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#457B9D");

                    b.Property<bool>("ShowContactButton")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowProductDetails")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSearchButton")
                        .HasColumnType("bit");

                    b.Property<string>("TabBackgroundColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#000000");

                    b.Property<string>("TabTextColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<string>("Tagline")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#1D3557");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitlesColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#000000");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrowserThemeColor = "#1D3557",
                            BusinessName = "DigiMenu Demo",
                            CompanyId = 1,
                            CountryCode = "CR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "CRC",
                            CurrencyLocale = "es-CR",
                            Decimals = (byte)0,
                            FormRequireAllergies = false,
                            FormRequireBirthday = false,
                            FormRequireComments = false,
                            FormRequireName = true,
                            FormRequirePersons = true,
                            FormRequirePhone = true,
                            FormRequireTable = false,
                            FormShowAllergies = false,
                            FormShowBirthday = false,
                            FormShowComments = true,
                            FormShowName = true,
                            FormShowPersons = true,
                            FormShowPhone = true,
                            FormShowTable = false,
                            HeaderBackgroundColor = "#1D3557",
                            HeaderStyle = (byte)1,
                            HeaderTextColor = "#FFFFFF",
                            IsDarkMode = false,
                            Language = "es",
                            MenuLayout = (byte)1,
                            MetaDescription = "El mejor menú digital para tu restaurante",
                            MetaTitle = "DigiMenu Demo",
                            PageBackgroundColor = "#F1FAEE",
                            PhoneCode = "+506",
                            PrimaryColor = "#E63946",
                            PrimaryTextColor = "#FFFFFF",
                            ProductDisplay = (byte)1,
                            SecondaryColor = "#457B9D",
                            ShowContactButton = true,
                            ShowProductDetails = true,
                            ShowSearchButton = true,
                            TabBackgroundColor = "#457B9D",
                            TabTextColor = "#FFFFFF",
                            Tagline = "Tu menú digital, siempre disponible",
                            TextColor = "#1D3557",
                            TimeZone = "America/Costa_Rica",
                            TitlesColor = "#1D3557"
                        });
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.StandardIcon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SvgContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StandardIcons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Facebook",
                            SvgContent = "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z'></path></svg>"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Instagram",
                            SvgContent = "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='2' y='2' width='20' height='20' rx='5' ry='5'></rect><path d='M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z'></path><line x1='17.5' y1='6.5' x2='17.51' y2='6.5'></line></svg>"
                        },
                        new
                        {
                            Id = 3,
                            Name = "WhatsApp",
                            SvgContent = "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 1 1-7.6-14h.1c4.3 0 7.9 3.5 8.4 7.7z'></path><path d='M17 16l-4-4 4-4'></path></svg>"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TikTok",
                            SvgContent = "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M9 12a4 4 0 1 0 4 4V4a5 5 0 0 0 5 5'></path></svg>"
                        },
                        new
                        {
                            Id = 5,
                            Name = "YouTube",
                            SvgContent = "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M22.54 6.42a2.78 2.78 0 0 0-1.95-1.96C18.88 4 12 4 12 4s-6.88 0-8.59.46A2.78 2.78 0 0 0 1.46 6.42 29 29 0 0 0 1 12a29 29 0 0 0 .46 5.58 2.78 2.78 0 0 0 1.95 1.96C5.12 20 12 20 12 20s6.88 0 8.59-.46a2.78 2.78 0 0 0 1.95-1.96A29 29 0 0 0 23 12a29 29 0 0 0-.46-5.58z'></path><polygon points='9.75 15.02 15.5 12 9.75 8.98 9.75 15.02'></polygon></svg>"
                        },
                        new
                        {
                            Id = 6,
                            Name = "X (Twitter)",
                            SvgContent = "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M4 4l16 16M4 20L20 4'/></svg>"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Web",
                            SvgContent = "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='10'></circle><line x1='2' y1='12' x2='22' y2='12'></line><path d='M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z'></path></svg>"
                        });
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#ffffff");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "IsDeleted");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#4CAF50",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Vegano"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#F44336",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Picante"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#9C27B0",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Alcohólico"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#FF9800",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Sin Gluten"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#F50057",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Popular"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#2196F3",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Nuevo"
                        });
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductTags", (string)null);
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.AppUser", b =>
                {
                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Category", b =>
                {
                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Company", "Company")
                        .WithMany("Categories")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.CompanyModule", b =>
                {
                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Company", "Company")
                        .WithMany("CompanyModules")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.PlatformModule", "PlatformModule")
                        .WithMany()
                        .HasForeignKey("PlatformModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("PlatformModule");
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.FooterLink", b =>
                {
                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Company", "Company")
                        .WithMany("FooterLinks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.StandardIcon", "StandardIcon")
                        .WithMany()
                        .HasForeignKey("StandardIconId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("StandardIcon");
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Product", b =>
                {
                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Reservation", b =>
                {
                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Company", "Company")
                        .WithMany("Reservations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Setting", b =>
                {
                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Company", "Company")
                        .WithOne("Setting")
                        .HasForeignKey("DigiMenuAPI.Infrastructure.Entities.Setting", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Tag", b =>
                {
                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Company", "Company")
                        .WithMany("Tags")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiMenuAPI.Infrastructure.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DigiMenuAPI.Infrastructure.Entities.Company", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CompanyModules");

                    b.Navigation("FooterLinks");

                    b.Navigation("Products");

                    b.Navigation("Reservations");

                    b.Navigation("Setting");

                    b.Navigation("Tags");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
